# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4afccbc0c42b7671eb17c8297d4829960fd0cec0775913dbc9d87a7de3be5ae1e9d01ecb2af83f513ce52f0412b0a8142df24fd4e45b2d0e90013715c946f64d

test:
  secret_key_base: 07d6c6938d63c61fa0a35982f2a3b7de07a83a1a75cf80e2c72856d20ebd71d0bfbb05a98fa080fdfa46a3729b00da77cbbe848ae63b68c5136511ed5c43c7b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
